spring:
  application:
    name: discovery-server

server:
  port: 8761

# Disable Eureka client registration and fetching registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
